version: "3"
services:
  javaps:
    build: .
    image: registry.wacodis.demo.52north.org/javaps:1.0.0
    container_name: javaps-container
    env_file:
      - wacodis-javaps.env
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    environment:
      # Publicly accessible URL of the service
      SERVICE_SERVICE_URL: http://javaps-container:8080/wacodis-javaps/service
      SERVICE_PROVIDER_INDIVIDUAL_NAME: Sebastian Drost
      SERVICE_PROVIDER_POSITION_NAME: First Line Supporter (24/7)
    volumes:
      - ./config/tools:/tmp/tools
      - ./config/gpf:/tmp/gpf
      # Workdir on docker host must be the same as the workdir within the javaPS container
      - /tmp/workdir:/tmp/workdir
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - shared
networks:
  shared:
    driver: bridge
